In [1]:
import numpy as np

In [2]:
#Question 1
arr = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
arr

In [7]:
#Question 2
x = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
y = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
np.vstack((x,y))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
#Question 3
np.hstack((x,y))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [10]:
#Question 4
array1d = arr.ravel()
array1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#Question 5
arr2 = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9],[10,11,12,13,14]])
newarr = arr2.reshape(-1)
newarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
#Question 6
arr3 = newarr.reshape(5,3)
arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [17]:
#Question 07
arr4 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
array_sq = arr4 * arr4
array_sq

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])

In [20]:
#Question 08
arr5 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24],[25,26,27,28,29,30]])
array_mean = np.mean(arr5)
array_mean

15.5

In [21]:
#Question 09
array_std = np.std(arr5)
array_std

8.65544144839919

In [22]:
#Question 10
array_median = np.median(arr5)
array_median

15.5

In [23]:
#Question 11
array_transpose = arr5.transpose()
array_transpose

array([[ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30]])

In [26]:
#Question 12
arr6 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
array_trace = np.trace(arr6)
array_trace

34

In [27]:
#Question 13
arr_det = np.linalg.det(arr6)
arr_det

0.0

In [30]:
#Question 14
per_5 = np.percentile(arr6,5)
per_95 = np.percentile(arr6,95)
print(per_5,per_95)

1.75 15.25


In [31]:
#Question 15
check = np.isnan(arr6)
check

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])